language: node_js
node_js:
  - '4.0'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
  - 'sudo $(which npm) install -g firebase-tools'
after_success:
  - firebase deploy --token '-K2FmmPbt2Rz4UM_4Tqt|162fb88fbd80345f1aeef21c75d231b8'
